#Schema for the configuration file of rsvp module.
rsvp.settings:
  type: config_object
  label: 'RSVP List Content Type Settings'
  mappings:
    allowed_types:
      type: sequence
      label: 'Content types RSVP Form can display on'
      sequence:
        type: string
        label: 'Content type'